config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
  end

  def create
    @article = Article.new(article_params)
    
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end    
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to articles_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br />
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>

<h2>
	<%= article.title %>
</h2>

<p>
	<%= article.text %>
</p>

<p>
	<%= link_to 'Show', article_path(article) %> | 
	<%= link_to 'Edit', edit_article_path(article) %> |
	<%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
</p>

<hr />

<% end %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br />
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
	<%= @article.text %>
</p>

<h2>Comments</h2>

<% @article.comments.each do |comment| %>
	<p>
		<i><%= comment.author %> said: </i><br />
		<%= comment.body %>
	</p>
<% end %>

<h2>Add comment</h2>
<p>
	<%= form_for([@article, @article.comments.build]) do |f| %>
		<p>
			<p>
				<%= f.label :author %><br />
				<%= f.text_field :author %>
			</p>

			<p>
				<%= f.label :body %><br />
				<%= f.text_area :body %>
			</p>

			<p>
				<%= f.submit %>
			</p>
		</p>
	<% end %>
</p>

app/views/contacts/create.html.erb
<p>Thanks!</p>

app/views/contacts/new.html.erb
<h1>Contact us</h1>

<%= form_for :contact, url: contacts_path do |f| %>
	<% if @contact && @contact.errors.any? %>
	<p>
		<ul>
		<% @contact.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</p>
	<% end %>
	
	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :message %><br />
		<%= f.text_area :message %>
	</p>

	<p>
		<%= f.submit 'Send message' %>
	</p>

<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>

app/views/pages/terms.html.erb
<h1>Terms of Service</h1>
<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
</p>